sudo: required
language: generic 
services:
  - docker

before_install:
#  - docker build -t ruchikong/react-test -f ./client/Dockerfile.dev ./client
  - docker-compose -f ./client/docker-compose-dev.yml up --build

script:
 - docker run  -e CI=true ruchikong/react-test npm test

after_success:
# - docker build -t ruchikong/prod-client ./client
# - docker build -t ruchikong/prod-server ./server
# - docker build -t ruchikong/prod-nginx ./nginx
# - docker build -t ruchikong/prod-worker ./worker

  - docker-compose -f docker-compose.yml up
  - docker-compose -f docker-compose.yml up --build
  - docker-compose -f docker-compose.yml down

# login to docker CLI
 - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
 # take images and push to docker hub
  
 - docker push ruchikong/prod-client
 - docker push ruchikong/prod-server
 - docker push ruchikong/prod-nginx
 - docker push ruchikong/prod-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "prod-docker"
  env: "Proddocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-589385579757"
  bucket-path: "prod-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY





